---
- name: Check if the GitHub CLI is installed
  shell: command -v gh
  register: gh_exists
  ignore_errors: yes

- name: Create /keyrings folder if it doesnt exist
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 755
  when: gh_exists is failed

- name: Config Repo
  become: true
  shell: | 
    # sudo mkdir -p -m 755 /etc/apt/keyrings
    wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
  when: gh_exists is failed

- name: Change permissions for the githubcli-archive-keyring.gpg
  file:
    path: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: "go+r"
  when: gh_exists is failed

- name: Add GitHub CLI repository to sources.list.d
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/github-cli.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    create: yes
  when: gh_exists is failed

- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
  when: gh_exists is failed

- name: Install Github CLI
  ansible.builtin.apt:
    name:
      gh
    state: present
  when: gh_exists is failed
