- name: Install Sway
  become: true
  ansible.builtin.apt:
    name: sway
    state: present

- name: Install Sway Utilities
  become: true
  ansible.builtin.apt:
    pkg:
      - wl-clipboard
      - wofi
      - swayimg
      - grim
      - slurp
      - swaybg
      - waybar
      - swayidle
      - swaylock
      - xdg-desktop-portal-wlr
      - sway-notification-center
      - pavucontrol
    state: present
