---
- name: check if go is installed
  shell: command -v go
  register: go_exists
  ignore_errors: yes

- name: download installer
  get_url:
    url: https://go.dev/dl/go1.22.2.linux-amd64.tar.gz
    dest: "{{ tmp_dir }}/go1.22.2.linux-amd64.tar.gz"
    mode: '0755'
  when: go_exists is failed

- name: remove previous installations
  shell: rm -rf /usr/local/go
  become: true
  when: go_exists is failed

- name: extract Go into /usr/local
  become: true
  ansible.builtin.unarchive:
    src: "{{ tmp_dir }}/go1.22.2.linux-amd64.tar.gz"
    dest: /usr/local/
  when: go_exists is failed

- name: clear downloaded go file
  ansible.builtin.file:
    path: "{{ tmp_dir }}/go1.22.2.linux-amd64.tar.gz"
    state: absent
